### DISCUSSION TITLE
ENV configuration to show People

### DISCUSSION THREAD

**Discussion by peteryacono-cc** [immichFrame/ImmichFrame#394] [Q&A] [answered]
Hi there,
I have a successful immich container installed via dockge on a Truenas server. 
In another container I have an immichframe container which does run successfully. 
What I'm struggling with is getting the *FRAME* to display only certain people. 
Immich itself has done all the analysing of the photos. I have a good library of people. I have named them. 

As I mentioned, the actual install is fine, however whenever I uncomment the 'people' variable and give it a name from my known people library within immich, it crashes the immichframe. Any help would be greatly appreciated. 
I've tried running it within one compose file and get similar results. 

Below is my compose file + environment variables. 
Along with the error code on the terminal. I get no error codes when I comment out the "People" variable. 

```
name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:latest
    restart: on-failure
    volumes:
      - /mnt/DEV/configs/immichframe:/app/Config
    # - PATH/TO/CUSTOMCSS/custom.css:/app/wwwroot/static/custom.css
    ports:
      - 2284:8080
    env_file:
      - .env
    environment:
      TZ: Australia/Sydney
networks: {}
```

```
ImmichServerUrl=(blanked for privacy)
ApiKey=(blanked for privacy)
# AuthenticationSecret=
Interval=8
TransitionDuration=2
ImageZoom=true
Layout=splitview
# DownloadImages=false
# ShowMemories=false
# ShowFavorites=false
# ShowArchived=false
# ImagesFromDays=
# ImagesFromDate=
# ImagesUntilDate=
# RenewImagesDuration=30
# Rating=5
# Albums=ALBUM1,ALBUM2
# ExcludedAlbums=ALBUM3,ALBUM4
# Webcalendars=https://calendar.mycalendar.com/basic.ics,webcal://calendar.mycalendar.com/basic.ics
# RefreshAlbumPeopleInterval=12
ShowClock=true
ClockFormat=hh:mm
ShowPhotoDate=true
PhotoDateFormat=yyyy-MM-dd
ShowImageDesc=true
People=Peter
ShowPeopleDesc=true
# ShowAlbumName=true
ShowImageLocation=true
ImageLocationFormat=City,State,Country
# PrimaryColor=#F5DEB3
# SecondaryColor=#000000
# Style=none
# BaseFontSize=17px
# WeatherApiKey=
ShowWeatherDescription=true
UnitSystem=Metric
WeatherLatLong=(blanked for privacy)
# Language=en
# Webhook=
```

TERMINAL OUTPUT: 
immichframe  | 
immichframe  | LogLevel: Information
immichframe  | 25-06-08 20:44:02 warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50] Using an in-memory repository. Keys will not be persisted to storage.
immichframe  | 25-06-08 20:44:02 warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
immichframe  | 25-06-08 20:44:02 warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35] No XML encryptor configured. Key {7e2490e1-3376-408f-8adc-0b9f363a78d8} may be persisted to storage in unencrypted form.
immichframe  | 25-06-08 20:44:02 info: Microsoft.Hosting.Lifetime[14] Now listening on: http://[::]:8080
immichframe  | 25-06-08 20:44:02 info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.
immichframe  | 25-06-08 20:44:02 info: Microsoft.Hosting.Lifetime[0] Hosting environment: Production
immichframe  | 25-06-08 20:44:02 info: Microsoft.Hosting.Lifetime[0] Content root path: /app
